import type { TestimonioCardProps } from "@/components/cards/TestimonioCard";

// Enum of testimonial identifiers (based on the Excel list)
// Add an entry here for each row in Excel (unique name per person)
export enum TestimonioId {
  LEONARDO_MANUEL = "Leonardo Manuel",
  MAGALY_AYERBE = "Magaly Ayerbe",
  MELISSA_CALDERON = "Melissa Calderon",
  MIGUEL_BUSTILLOS = "Miguel Bustillos",
  KATHERINE_CRUZ = "Katherine Cruz",
  ADELI_ZAMORA = "Adeli Zamora",
  JONATHAN_ORA = "Jonathan Ora",
  ESTEFANI_AYQUIPA = "Estefani Ayquipa",
  FRANCIS_MATEO = "Francis Mateo",
  JOSE_URETA = "Jose Ureta",
  PAUL_CAM = "Paul Cam",
  ANDREA_DE_LAS_CASAS = "Andrea de las casas",
  CARLA_TAFUR = "Carla Tafur",
  ANGELO_MORENO = "Angelo Moreno",
  VERA_LUCIA_TOVAR = "Vera Lucia Tovar",
  ERICK_PALOMINO = "Erick Palomino",
  ANONIMO = "Anónimo",
  YAZMIN_OCAMPO = "Yazmin Ocampo",
  LEENKIN = "Leenkin",
  MAJO_ZAMBRANO = "Majo Zambrano",
  SANDRA_SEMINARIO = "Sandra Seminario",
  DAN_RODRIGUEZ = "Dan Rodriguez",
  ANDREWS_POSTILLOS = "Andrews postillos",
  STHEFANNY_CISNEROS = "Sthefanny Cisneros",
  HANS_ALFARO = "Hans Alfaro",
  ANTONIO_CABRERA = "Antonio Cabrera",
}

// Type-safe map of data for each testimonial
// Includes the photo (avatarSrc) as representative image of the testimonial
export const TESTIMONIOS: Record<TestimonioId, TestimonioCardProps> = {
  [TestimonioId.MELISSA_CALDERON]: {
    quote: `Hugooo, When I joined the company, I found a leader who went beyond expectations: someone agile, resilient and deeply inspiring. You were a guide in my first steps, teaching me not only the path, but also the deep meaning of being a true leader.
    I deeply admire your ability to face setbacks, both personal and professional, with courage and humility, transforming them into valuable lessons. You learned to recognize your mistakes, something that not only made you stronger, but also strengthened those of us fortunate enough to work alongside you.
    Your dedication, commitment and passion for inspiring your team are qualities that marked my career and that today, looking back, I am immensely grateful for. You helped me understand that leading is not simply directing, but serving, motivating and building with empathy and conviction.
    I remember you with respect and admiration, because beyond professional achievements, you left a mark on me that transcends the work environment. Thank you for your time, for your teachings and for demonstrating that a leader is not born, but is built with each decision, with each acknowledged mistake and with each person you inspire.
    A warm hug from afar. Meli.`,
    authorName: "Melissa Calderon",
    role: "I was part of your team.",
    avatarSrc: "/images/testimonials/melissa-calderon.jpg",
    avatarAlt: "Profile photo of Melissa Calderon",
    linkedInUrl: "https://www.linkedin.com/in/meliem/",
    tags: ["Human leader", "Vulnerability", "Empathy"],
    highlight: "You learned to recognize your mistakes",
  },
  [TestimonioId.MAGALY_AYERBE]: {
    quote: `When I met you, in the first interview, I think it was instant chemistry, despite being told I'm sociable, I feel very distant when I meet someone for the first time, but with you it was different.
    Starting to work together made me see and feel that we have a similar character, you helped me recognize and enhance my skills as a strategist and the ability to provide immediate effective solutions, you strengthened my agility skill.
    You are that "adult shark" that I admire, who over time, intentionally and unintentionally, has been leaving me life and professional teachings that I carry and put into practice.
    Thank you for everything Hugo.`,
    authorName: "Magaly Ayerbe",
    role: "I was part of your team.",
    avatarSrc: "/images/testimonials/magaly-ayerbe.jpg",
    avatarAlt: "Profile photo of Magaly Ayerbe",
    linkedInUrl: "https://www.linkedin.com/in/magaly-ayerbe-malaver/",
    tags: ["Empowerment", "Agility", "Mentoring"],
    highlight: "recognize and enhance my skills",
  },
  [TestimonioId.LEONARDO_MANUEL]: {
    quote: `It was a nice experience like all work has its ups and downs. But very happy with the way of supporting and guiding to be better professionals`,
    authorName: "Leonardo Manuel",
    role: "I was part of your team.",
    avatarSrc: "/images/testimonials/leonardo-manuel.jpg",
    avatarAlt: "Profile photo of Leonardo Manuel",
    linkedInUrl:
      "https://www.linkedin.com/in/leonardo-manuel-alvarez-27bb43123/",
    tags: ["Guidance", "Professional growth"],
    highlight: "supporting and guiding to be better",
  },
  [TestimonioId.MIGUEL_BUSTILLOS]: {
    quote: `You helped me in my professional career, to feel like part of a family in a work team, to have more confidence in my abilities and to be better every day professionally`,
    authorName: "Miguel Bustillos",
    role: "I was part of your team.",
    avatarSrc: "/images/testimonials/miguel-bustillos.jpg",
    avatarAlt: "Profile photo of Miguel Bustillos",
    linkedInUrl: "https://www.linkedin.com/in/miguel-angel-bustillos-alayo/",
    tags: ["Family", "Confidence", "Growth"],
    highlight: "part of a family",
  },
  [TestimonioId.KATHERINE_CRUZ]: {
    quote: `Well, I'll talk about when I joined the company, as it really changed my work mentality. Seeing and feeling part of the family we were forming was very encouraging to learn to be part of.... I know there are many changes but I have tried to adapt to what comes as I feel that there will always be something better with you as a leader 😌💪🏽`,
    authorName: "Katherine Cruz",
    role: "I interviewed you in a selection process.",
    avatarSrc: "/images/avatar-female.svg",
    avatarAlt: "Profile photo of Katherine Cruz",
    linkedInUrl: "https://www.linkedin.com",
    tags: ["Mindset", "Family", "Adaptability"],
    highlight: "changed my work mentality",
  },
  [TestimonioId.ADELI_ZAMORA]: {
    quote: `Working at On Road has taught me to listen better and connect authentically with each client. Throughout my experience working at On Road I have learned that it's not just about selling, but about helping people. This experience has helped me a lot both in my personal and professional growth. And I thank Hugo for giving me the opportunity to belong to this great team, for all his teachings and for trusting me and the entire Peru team from the beginning.`,
    authorName: "Adeli Zamora",
    role: "I was part of your team.",
    avatarSrc: "/images/testimonials/adeli-zamora.jpg",
    avatarAlt: "Profile photo of Adeli Zamora",
    linkedInUrl:
      "https://www.linkedin.com/in/adeli-marcy-zamora-calderón-133a3318b/",
    tags: ["Growth", "Trust", "Opportunity"],
    highlight: "trusting me",
  },
  [TestimonioId.JONATHAN_ORA]: {
    quote: `Never stop sharing that encouraging attitude! There will always be someone who needs to see it and be motivated to be part of the change!`,
    authorName: "Jonathan Ora",
    role: "I was part of your team.",
    avatarSrc: "/images/testimonials/jonathan-ora.jpg",
    avatarAlt: "Profile photo of Jonathan Ora",
    linkedInUrl: "https://www.linkedin.com/in/pjhonaob/",
    tags: ["Motivation", "Positive attitude", "Inspiration"],
    highlight: "encouraging attitude",
  },
  [TestimonioId.ESTEFANI_AYQUIPA]: {
    quote: `Personally if I didn't agree with something I had the confidence to express my opinion to you because I knew you would have that openness to listen to me. Likewise, I felt on many occasions that you valued my commitment to my work and the support I was able to provide when requested on some occasions. I believe that when one feels valued (in this case by you) one supports with pleasure in what they may ask because you feel that your work, commitment, effort and all your effort is reciprocated.`,
    authorName: "Estefani Ayquipa",
    role: "I was part of your team.",
    avatarSrc: "/images/testimonials/estefani-ayquipa.jpg",
    avatarAlt: "Profile photo of Estefani Ayquipa",
    linkedInUrl:
      "https://www.linkedin.com/in/mary-estefani-ayquipa-maceda-8697ab1b7/",
    tags: ["Psychological safety", "Recognition", "Openness"],
    highlight: "confidence to express my opinion",
  },
  [TestimonioId.FRANCIS_MATEO]: {
    quote: `Thank you for your guidance, always practical and results-oriented. You helped me focus on what's important and keep moving forward.`,
    authorName: "Francis Mateo",
    role: "I was part of your team.",
    avatarSrc: "/images/testimonials/francis-mateo.jpg",
    avatarAlt: "Profile photo of Francis Mateo",
    linkedInUrl: "https://www.linkedin.com/in/francis-mateo-ayala/",
    tags: ["Focus", "Results", "Pragmatism"],
    highlight: "focus on what's important",
  },
  [TestimonioId.JOSE_URETA]: {
    quote: `From the beginning I felt supported in every way, you encouraged me to face new challenges and I had the confidence to propose and debate in a safe environment.`,
    authorName: "Jose Ureta",
    role: "I was part of your team.",
    avatarSrc: "/images/testimonials/jose-ureta.jpg",
    avatarAlt: "Profile photo of Jose Ureta",
    linkedInUrl: "https://www.linkedin.com/in/josé-antonio-ureta-chipana/",
    tags: ["Psychological safety", "Challenges", "Trust"],
    highlight: "safe environment",
  },
  [TestimonioId.PAUL_CAM]: {
    quote: `The job opportunity you gave me was the professional step I needed to experience the basics and advanced things of the field, it helped me find a path in which I feel comfortable and eager to specialize more and obtain more opportunities for professional growth. That first support and constant motivation will always be appreciated by me`,
    authorName: "Paul Cam",
    role: "I was part of your team.",
    avatarSrc: "/images/testimonials/paul-cam.jpg",
    avatarAlt: "Profile photo of Paul Cam",
    linkedInUrl: "https://www.linkedin.com/in/paul-cam/",
    tags: ["Opportunity", "Professional growth", "Gratitude"],
    highlight: "the professional step I needed",
  },
  [TestimonioId.ANDREA_DE_LAS_CASAS]: {
    quote: `Thank you for everything you taught me Hugo, for trusting me for the work I did and for always being willing to help when needed. Success!`,
    authorName: "Andrea de las casas",
    role: "I was part of your team.",
    avatarSrc: "/images/testimonials/andrea-de-las-casas.jpg",
    avatarAlt: "Profile photo of Andrea de las casas",
    linkedInUrl:
      "https://www.linkedin.com/in/andrea-de-las-casas-koo-9637499a/",
    tags: ["Trust", "Support", "Gratitude"],
    highlight: "trusting me",
  },
  [TestimonioId.CARLA_TAFUR]: {
    quote: `Thank you for the trust and all the teachings, the human quality you have is invaluable. Success in everything you undertake Hugo!!!`,
    authorName: "Carla Tafur",
    role: "I was part of your team.",
    avatarSrc: "/images/testimonials/carla-tafur.jpg",
    avatarAlt: "Profile photo of Carla Tafur",
    linkedInUrl: "https://www.linkedin.com/in/carla-cotrina-tafur-7178b11a9/",
    tags: ["Human quality", "Trust", "Teachings"],
    highlight: "human quality",
  },
  [TestimonioId.ANGELO_MORENO]: {
    quote: `You were a fundamental part of my professional development, I learned a lot from you, from the experience you shared with me and the opportunities you gave me to grow. I really appreciate your unconditional support and trust. Thank you for the friendship and for being a great professional.`,
    authorName: "Angelo Moreno",
    role: "I was part of your team.",
    avatarSrc: "/images/avatar-male.svg",
    avatarAlt: "Profile photo of Angelo Moreno",
    linkedInUrl: "https://www.linkedin.com",
    tags: ["Professional development", "Opportunities", "Friendship"],
    highlight: "unconditional support and trust",
  },
  [TestimonioId.VERA_LUCIA_TOVAR]: {
    quote: `Hugo not only is my younger brother, I have also seen his trajectory in transforming teams and organizational cultures. His genuine approach has impacted not only professionally, but also in the families of those who have worked with him. As a coach, he helps people find...`,
    authorName: "Vera Lucia Tovar",
    role: "I'm your sister and close witness to your work.",
    avatarSrc: "/images/image12.png",
    avatarAlt: "Profile photo of Vera Lucia Tovar",
    linkedInUrl: "https://www.linkedin.com",
    tags: ["Family impact", "Transformation", "Purpose"],
    highlight: "impacted families",
  },
  [TestimonioId.ERICK_PALOMINO]: {
    quote: `Thank you Hugo!! It was an amazing experience to work as a team, seeing how much you cared about each person on the team 😀, I really appreciate that you were always concerned to know if we were well, if we had doubts and how to support us in what we needed, it was very gratifying to have been part of your team.`,
    authorName: "Erick Palomino",
    role: "I was part of your team.",
    avatarSrc: "/images/image13.png",
    avatarAlt: "Profile photo of Erick Palomino",
    linkedInUrl: "https://www.linkedin.com",
    tags: ["Care", "Support", "Team"],
    highlight: "cared about each person",
  },
  [TestimonioId.ANONIMO]: {
    quote: `Thank you for the opportunity you gave me, you were a great leader, you always guided and encouraged me in every aspect 🤗`,
    authorName: "Anonymous",
    role: "I was part of your team.",
    avatarSrc: "/images/default-avatar.png",
    avatarAlt: "Anonymous profile",
    linkedInUrl: "",
    tags: ["Leadership", "Guidance", "Encouragement"],
    highlight: "great leader",
  },
  [TestimonioId.YAZMIN_OCAMPO]: {
    quote: `Thank you very much Hugo for your trust and for the opportunity you gave me to be part of your team. It was a pleasant experience. Success in everything you undertake!`,
    authorName: "Yazmin Ocampo",
    role: "I was part of your team.",
    avatarSrc: "/images/testimonials/yazmin-ocampo.jpg",
    avatarAlt: "Profile photo of Yazmin Ocampo",
    linkedInUrl: "https://www.linkedin.com/in/yazmin-ocampo-a248271a7/",
    tags: ["Trust", "Opportunity", "Pleasant experience"],
    highlight: "opportunity you gave me",
  },
  [TestimonioId.LEENKIN]: {
    quote: `Honestly, I really value having coincided with someone like you Hugo, you taught me the importance of facing my fears and trying things even if they are uncomfortable. I think it's valuable for a leader to be willing to show their vulnerable side. Thanks for everything bro! 🙌`,
    authorName: "Leenkin",
    role: "I was part of your team.",
    avatarSrc: "/images/avatar-male.svg",
    avatarAlt: "Profile photo of Leenkin",
    linkedInUrl: "https://www.linkedin.com",
    tags: ["Vulnerability", "Courage", "Authenticity"],
    highlight: "show their vulnerable side",
  },
  [TestimonioId.MAJO_ZAMBRANO]: {
    quote: `I'm grateful for the opportunity you gave me and all the trust you placed in me. Even though I didn't stay longer, I carry with me everything I learned with you. Thank you Hugo 🫶`,
    authorName: "Majo Zambrano",
    role: "I was part of your team.",
    avatarSrc: "/images/testimonials/majo-zambrano.jpg",
    avatarAlt: "Profile photo of Majo Zambrano",
    linkedInUrl: "https://www.linkedin.com/in/maria-jose-zambrano-escobar/",
    tags: ["Opportunity", "Trust", "Learning"],
    highlight: "trust you placed in me",
  },
  [TestimonioId.SANDRA_SEMINARIO]: {
    quote: `I value a lot that you saw my potential for a role I had never performed (sales and commercial) and you trusted me to give me that opportunity. I learned a lot from your drive, your tireless search for results, your competitive and strategic vision. I admire your versatility to adapt to change!`,
    authorName: "Sandra Seminario",
    role: "I was part of your team.",
    avatarSrc: "/images/testimonials/sandra-seminario.jpg",
    avatarAlt: "Profile photo of Sandra Seminario",
    linkedInUrl: "https://www.linkedin.com/in/sangaselu/",
    tags: ["Potential", "Trust", "Strategic vision"],
    highlight: "saw my potential",
  },
  [TestimonioId.DAN_RODRIGUEZ]: {
    quote: `You gave me the opportunity to be part of an incredible team, where I learned a lot and grew professionally. Thank you for the trust and for always being willing to help when needed. Success in everything you do Hugo!`,
    authorName: "Dan Rodriguez",
    role: "I was part of your team.",
    avatarSrc: "/images/testimonials/dan-rodriguez.jpg",
    avatarAlt: "Profile photo of Dan Rodriguez",
    linkedInUrl:
      "https://www.linkedin.com/in/dan-azareel-rodriguez-hernandez-b09015135/",
    tags: ["Opportunity", "Professional growth", "Support"],
    highlight: "incredible team",
  },
  [TestimonioId.ANDREWS_POSTILLOS]: {
    quote: `I am your brother and close witness to your work. Not only have I seen your trajectory in transforming teams and organizational cultures. Your genuine approach has impacted not only professionally, but also in the families of those who have worked with you. As a coach, you help people find...`,
    authorName: "Andrews Postillos",
    role: "I'm your brother and close witness to your work.",
    avatarSrc: "/images/avatar-male.svg",
    avatarAlt: "Profile photo of Andrews Postillos",
    linkedInUrl:
      "https://www.linkedin.com/in/andrews-leonard-postillos-estrada-416537333/",
    tags: ["Family impact", "Transformation", "Community"],
    highlight: "impacted families",
  },
  [TestimonioId.STHEFANNY_CISNEROS]: {
    quote: `Thank you for the opportunity and all the learning. Your commitment to the team and your ability to inspire are admirable. Success in all your projects Hugo!`,
    authorName: "Sthefanny Cisneros",
    role: "I was part of your team.",
    avatarSrc: "/images/testimonials/sthefanny-cisneros.jpg",
    avatarAlt: "Profile photo of Sthefanny Cisneros",
    linkedInUrl:
      "https://www.linkedin.com/in/sthefanny-cisneros-salazar-3422b6161/",
    tags: ["Opportunity", "Learning", "Inspiration"],
    highlight: "ability to inspire",
  },
  [TestimonioId.HANS_ALFARO]: {
    quote: `Thank you Hugo for the trust and for giving me the opportunity to be part of your team. I learned a lot from you and I really appreciate your support. Success in everything you do!`,
    authorName: "Hans Alfaro",
    role: "I was part of your team.",
    avatarSrc: "/images/testimonials/hans-alfaro.jpg",
    avatarAlt: "Profile photo of Hans Alfaro",
    linkedInUrl: "https://www.linkedin.com/in/hans-alfaro-23a2b7135/",
    tags: ["Trust", "Opportunity", "Learning"],
    highlight: "learned a lot from you",
  },
  [TestimonioId.ANTONIO_CABRERA]: {
    quote: `Thank you for the opportunity and for trusting my work. I learned a lot working with you and I really value the experience. Success in all your projects Hugo!`,
    authorName: "Antonio Cabrera",
    role: "I was part of your team.",
    avatarSrc: "/images/avatar-male.svg",
    avatarAlt: "Profile photo of Antonio Cabrera",
    linkedInUrl: "https://www.linkedin.com",
    tags: ["Opportunity", "Trust", "Experience"],
    highlight: "value the experience",
  },
};

// Exported list of testimonials in the desired display order
export const TESTIMONIOS_LIST: TestimonioCardProps[] = [
  TESTIMONIOS[TestimonioId.LEONARDO_MANUEL],
  TESTIMONIOS[TestimonioId.ANDREWS_POSTILLOS],
  TESTIMONIOS[TestimonioId.ESTEFANI_AYQUIPA],
  TESTIMONIOS[TestimonioId.MIGUEL_BUSTILLOS],
  TESTIMONIOS[TestimonioId.ANTONIO_CABRERA],
  TESTIMONIOS[TestimonioId.DAN_RODRIGUEZ],
  TESTIMONIOS[TestimonioId.MELISSA_CALDERON],
  TESTIMONIOS[TestimonioId.VERA_LUCIA_TOVAR],
  TESTIMONIOS[TestimonioId.MAJO_ZAMBRANO],
  TESTIMONIOS[TestimonioId.LEENKIN],
  TESTIMONIOS[TestimonioId.PAUL_CAM],
  TESTIMONIOS[TestimonioId.ADELI_ZAMORA],
  TESTIMONIOS[TestimonioId.ANGELO_MORENO],
  TESTIMONIOS[TestimonioId.STHEFANNY_CISNEROS],
  TESTIMONIOS[TestimonioId.SANDRA_SEMINARIO],
  TESTIMONIOS[TestimonioId.YAZMIN_OCAMPO],
  TESTIMONIOS[TestimonioId.JOSE_URETA],
  TESTIMONIOS[TestimonioId.ERICK_PALOMINO],
  TESTIMONIOS[TestimonioId.FRANCIS_MATEO],
  TESTIMONIOS[TestimonioId.MAGALY_AYERBE],
  TESTIMONIOS[TestimonioId.JONATHAN_ORA],
  TESTIMONIOS[TestimonioId.CARLA_TAFUR],
  TESTIMONIOS[TestimonioId.ANDREA_DE_LAS_CASAS],
  TESTIMONIOS[TestimonioId.HANS_ALFARO],
  TESTIMONIOS[TestimonioId.KATHERINE_CRUZ],
];
